services:
  postgres:
    container_name: postgres2
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=shgpu_table
    ports:
      - 5432:5432
    volumes:
      - .:/var/lib/postgresql/shgpu-table
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shgpu-table"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512MB
    networks:
      - shgpu-table-dev
  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres:5432
      - ADMINER_PLUGINS=enum-types enum-option json-column
    networks:
      - shgpu-table-dev
networks:
  shgpu-table-dev:
    driver: bridge