name: ESLINT
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - uses: actions/checkout@v3
      - name: Install modules
        run: pnpm install
      - name: Run ESLint
        run: pnpx eslint
